version: "3.8"
services:
  backend:
    image: "areeb110/springboot-react-fullstack:21.5.2023.6.6.27"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
