version: "3.8"
services:
  backend:
    image: "areeb110/springboot-react-fullstack:28.5.2023.17.55.10"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
