version: "3.8"
services:
  backend:
    image: "areeb110/springboot-react-fullstack:26.5.2023.0.19.16"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
